# Generated by Django 4.2.3 on 2023-07-31 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_cartitem_cart_remove_cartitem_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('TS', 'T-shirt'), ('SH', 'Shoes'), ('CA', 'Caps'), ('JE', 'Jeans')], max_length=2),
        ),
    ]
