# Generated by Django 4.2.3 on 2023-08-02 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Lima', 'LI'), ('Arequipa', 'AQP'), ('Cusco', 'CU'), ('Trujillo', 'T'), ('Chiclayo', 'CL'), ('Piura', 'P')], max_length=100),
        ),
    ]
